web-app/miniAmazon/cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
        path('add/<int:good_id>/', views.add_cart, name='add_cart'),
        path('', views.cart_detail, name="cart_detail"),
        path('remove/<int:good_id>/', views.cart_remove, name="cart_remove"),
        path('full_remove/<int:good_id>/', views.full_remove, name="full_remove"),
        path('order/', views.create_order, name="create_order"),
        path('order/accept_order/', views.accept_order, name="accept_order"),
        #path('order/accept_order/order_success/', views.order_success, name="order_success"),
        ]

web-app/miniAmazon/miniAmazon/urls.py
from django.contrib import admin
from django.urls import path, include
from shop import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('shop/', include('shop.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
    path('account/create/', views.signupView, name='signup'),
    path('account/login/', views.signinView, name='signin'),
    path('account/logout/', views.signoutView, name='signout'),
    path('orderhistory/', views.orderhistoryView, name='orderhistoryView'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web-app/miniAmazon/search_app/urls.py
from django.urls import path
from . import views

app_name='search_app'

urlpatterns =[
        path('', views.searchResult, name='searchResult'),
        path('createNewCat/', views.createNewCat, name='createNewGat'),
        path('searchOrder/', views.searchOrder, name='searchOrder'),
        path('createNewCat/createNewGood/', views.createNewGood, name='createNewGood'),
        ]

web-app/miniAmazon/shop/urls.py
from django.urls import path
from . import views

app_name='shop'

urlpatterns =[
        path('', views.allGoodCat, name='allGoodCat'),
        path('<slug:c_slug>/', views.allGoodCat, name='goods_by_category'),
        path('<slug:c_slug>/<slug:good_slug>/', views.GoodCatDetail, name ='GoodCatDetail'), 
]

web-app/miniAmazon/shop/models.py
from django.db import models
from django.urls import reverse
from django.forms import ModelForm
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=120, unique=True)
    slug = models.SlugField(max_length=119, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True, default='category/classify.png')

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return '{}'.format(self.name)

    def get_url(self):
        return reverse('shop:goods_by_category', args=[self.slug])

class Good(models.Model):
    ID = models.AutoField(primary_key=True, unique=True)
    description = models.CharField(max_length=120, unique=True) #good name
    slug = models.SlugField(max_length=120, unique=True)
    detail = models.TextField(blank=True)  #description
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product', blank=True, default='product/Amazon-icon.png')
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated =models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('description',)
        verbose_name = 'good'
        verbose_name_plural = 'goods'

    def __str__(self):
        return '{}'.format(self.description)
    
    def get_url(self):
        return reverse('shop:GoodCatDetail', args=[self.category.slug, self.slug]) 

class Stock(models.Model):
    gid = models.IntegerField()
    whid = models.PositiveIntegerField()
    amount = models.PositiveIntegerField(default=0)

class Aorder(models.Model):
    ordernum    = models.AutoField(primary_key=True)
    userid      = models.IntegerField(blank=True, null=True)
    ID          = models.IntegerField() 
    description = models.CharField(max_length=120)
    amount      = models.IntegerField()
    ups         = models.CharField(max_length=120, blank=True, null=True) #ups account id
    whid        = models.IntegerField(blank=True, null=True)
    desx        = models.IntegerField(default=0)
    desy        = models.IntegerField(default=0)
    goodid      = models.IntegerField(blank=True, null=True)
    truckid     = models.IntegerField(blank=True, null=True)
    truck_ready = models.BooleanField(default=False)
    pack_ready  = models.BooleanField(default=False)
    load_ready  = models.BooleanField(default=False)
    delivered   = models.BooleanField(default=False)
    email       = models.EmailField(default=None)

class Uorder(models.Model):
    ordernum    = models.IntegerField(primary_key=True)
    ID          = models.IntegerField()
    description = models.CharField(max_length=120)
    amount      = models.IntegerField()
    ups         = models.CharField(max_length=120)
    whid        = models.IntegerField()
    desx        = models.IntegerField()
    desy        = models.IntegerField()

class Warehouse(models.Model):
    whid        = models.IntegerField()
    x           = models.IntegerField()
    y           = models.IntegerField()

 

web-app/miniAmazon/shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.db import models
from django.forms import ModelForm
from shop.models import Aorder

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=100, required=True)
    last_name  = forms.CharField(max_length=100, required=True)
    email      = forms.EmailField(max_length=254, help_text='eg. youremail@anyemail.com')
    

    class Meta:
        model =User
        fields = ('first_name', 'last_name', 'email', 'username', 'password1', 'password2')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        es = User.objects.filter(email= email)
        if es.exists():
            raise forms.ValidationError("Email is taken.")
        return email

class AorderForm(ModelForm):
    class Meta:
        model = Aorder
        fields = ['ups', 'desx', 'desy', 'email']

web-app/miniAmazon/shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Category,Good, Aorder
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.contrib.auth.models import Group, User
from .forms import SignUpForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import auth
from django.db.models import Q
from cart.models import Cart

 
def index(request):
    text_var = 'Mini Amazon'
    return HttpResponse(text_var)

def allGoodCat(request, c_slug=None):
    c_page = None
    goods_list = None
    if c_slug!=None:
        c_page = get_object_or_404(Category, slug=c_slug)
        goods_list  = Good.objects.filter(category=c_page, available=True)
    else:
        goods_list = Good.objects.all().filter(available=True)
    paginator = Paginator(goods_list, 6)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try:
        goods = paginator.page(page)
    except(EmptyPage, InvalidPage):
        goods = paginator.page(paginator.num_pages)
    return render(request, 'shop/category.html', {'category':c_page, 'goods':goods})

def GoodCatDetail(request, c_slug, good_slug):
    try:
        print(c_slug)
        good = Good.objects.get(category__slug=c_slug, slug=good_slug)
    except Exception as e:
        raise e
    return render(request, 'shop/good.html', {'good': good})

def signupView(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            email    = form.cleaned_data.get('email')
            signup_user = User.objects.get(username=username)        
            # customer_group = Group.objects.get(name='Customer')
            # customer_group.user_set.add(signup_user)
    else:
        form = SignUpForm()
    return render(request, 'accounts/signup.html', {'form':form})

def signinView(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request,user)
                return redirect('shop:allGoodCat')
            else:
                return redirect('signup')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/signin.html', {'form':form})

def signoutView(request):
    auth.logout(request)
    return redirect('signin')

def orderhistoryView(request):
    c_user = request.user
    order_history_list = Aorder.objects.all().filter(Q(userid__exact=c_user.id) | Q(email__exact=c_user.email))
    return render(request, 'shop/order_history.html', {'order_history_list': order_history_list })

web-app/miniAmazon/shop/templates/base.html
{% load staticfiles%}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="{% block metadescription %}{% endblock %}">
	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'css/custom.css' %}">
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome-all.min.css' %}">
	<title>{% block title %}{% endblock %}</title>
</head>
<body>
	<div class="container">
		<div class="container-fluid bg-light navbar-fixed-top my_top_navbar_div">
			{% include 'top-navbar.html' %}
		</div>
		{% include 'header.html' %}
		{% include 'navbar.html' %}
		{% block content%}
		{% endblock%}
	</div>
	{% include 'footer.html' %}
	<!-- Optional JavaScript -->
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
	<script src="{% static 'js/popper.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

web-app/miniAmazon/shop/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
	<p class="text-center">&copy; Mini Amazon. All Rights Reserved.</p>
</div>

web-app/miniAmazon/shop/templates/header.html
{% load staticfiles %}
<header>
	<center>	
		<a href="{% url 'shop:allGoodCat' %}"><img src="{% static 'img/Amazon-Smile-Logo.png' %}" width="auto" height="100px" alt="Mini Amazon"></a>
	</center>

web-app/miniAmazon/shop/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #E9E9E9">
	    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item dropdown {% if 'shop' in request.path %}active{% endif %}">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					Amazon Shop
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
					{% if request.user.is_authenticated and request.user.first_name %}
						<a class="dropdown-item" href="{% url 'orderhistoryView' %}">Order History</a>
					{% endif %}	
						<a class="dropdown-item" href="{% url 'shop:allGoodCat' %}">All Goods</a>
						{% for cat in links %}
						<a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>
						{% endfor %}
					</div>												
				</li>
				<li class="nav-item">																         
					<a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fas fa-shopping-cart"></i>({{item_count}})</a>
				</li>
			</ul>
			<form class="form-inline my-2 my-lg-0" action="{% url 'search_app:searchOrder' %}" method="get">
			{% csrf_token %}
			<input class="form-control mr-sm-2" type="search" placeholder="Trace your shipment" aria-label="Search" name="q">
				<button class="btn btn-secondary my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
			</form>
			<form class="form-inline my-2 my-lg-0" action="{% url 'search_app:searchResult' %}" method="get">
			{% csrf_token %}
				<input class="form-control mr-sm-2" type="search" placeholder="Search Good" aria-label="Search" name="q">
				<button class="btn btn-secondary my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
			</form>
		</div>
</nav>

<!--<nav>-->
	<!--<ul>-->
		<!--<li><a href="{% url 'shop:allGoodCat' %}">All Goods</a></li>-->
		<!--{% for cat in links %}-->
			<!--<li><a href="{{cat.get_url}}">{{cat.name}}</a></li>-->
		<!--{% endfor %}-->
		<!--<li>Your Cart()</li>-->
	<!--</ul>-->
<!--</nav><br>-->

web-app/miniAmazon/shop/templates/top-navbar.html
<div class="container">
	<div class="my_custom_menu">
		<ul>
			{% if request.user.is_authenticated and request.user.first_name %}
			<li>
				Welcome, {{request.user.first_name}}<i class="fas fa-user-circle"></i>
			</li>
			<li>
				<a href="{% url 'signout'%}">Sign Out<i class="fas fa-sign-out-alt"></i></a>
			</li>
			{% else %}
			<li>
				<a href="{% url 'signup' %}">Sign Up<i class="fas fa-user-plus"></i></a>
			</li>
			<li>
				<a href="{% url 'signin' %}">Sign In<i class="fas fa-sign-in-alt"></i></a>
			</li>
			{% endif %}
		</ul>		
	</div>
</div>