web-app/miniAmazon/cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
        path('add/<int:good_id>/', views.add_cart, name='add_cart'),
        path('', views.cart_detail, name="cart_detail"),
        path('remove/<int:good_id>/', views.cart_remove, name="cart_remove"),
        path('full_remove/<int:good_id>/', views.full_remove, name="full_remove"),
        path('order/', views.create_order, name="create_order"),
        path('order/accept_order/', views.accept_order, name="accept_order"),
        #path('order/accept_order/order_success/', views.order_success, name="order_success"),
        ]

web-app/miniAmazon/miniAmazon/urls.py
from django.contrib import admin
from django.urls import path, include
from shop import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('shop/', include('shop.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
    path('account/create/', views.signupView, name='signup'),
    path('account/login/', views.signinView, name='signin'),
    path('account/logout/', views.signoutView, name='signout'),
    path('orderhistory/', views.orderhistoryView, name='orderhistoryView'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web-app/miniAmazon/shop/urls.py
from django.urls import path
from . import views

app_name='shop'

urlpatterns =[
        path('', views.allGoodCat, name='allGoodCat'),
        path('<slug:c_slug>/', views.allGoodCat, name='goods_by_category'),
        path('<slug:c_slug>/<slug:good_slug>/', views.GoodCatDetail, name ='GoodCatDetail'), 
]

web-app/miniAmazon/cart/models.py
from django.db import models
from shop.models import Good

class Cart(models.Model):
    cart_id = models.CharField(max_length=120, blank=True)
    date_added = models.DateField(auto_now_add=True)
    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    good = models.ForeignKey(Good, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    amount = models.IntegerField()
    active = models.BooleanField(default=True)
    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.amount

    def __str__(self):
        return self.good

web-app/miniAmazon/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shop.models import Good
from .models import Cart, CartItem
from shop.forms import AorderForm
from django.conf import settings
from shop.models import Good, Aorder, Warehouse
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import send_mail

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request, good_id):
    good = Good.objects.get(ID=good_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
                cart_id = _cart_id(request)
                )
        cart.save()
    try:
        cart_item = CartItem.objects.get(good=good, cart=cart)
        cart_item.amount += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
                good = good,
                amount = 1,
                cart = cart,
                )
        cart_item.save() 
    return redirect('cart:cart_detail')

def cart_detail(request, total=0, counter=0, cart_items = None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += cart_item.amount
            counter += cart_item.amount
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items = cart_items, total = total, counter = counter))


def cart_remove(request, good_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    good = get_object_or_404(Good, ID=good_id)
    cart_item = CartItem.objects.get(good=good, cart=cart)
    if cart_item.amount > 1:
        cart_item.amount -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def full_remove(request, good_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    good = get_object_or_404(Good, ID=good_id)
    cart_item = CartItem.objects.get(good=good, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')
  
# Create your views here.:wq

def create_order(request, total=0, counter=0, cart_items = None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += cart_item.amount
            counter += cart_item.amount
    except ObjectDoesNotExist:
        pass
    aorderform = AorderForm()
    return render(request, 'order.html', dict(aorderform=aorderform, cart_items = cart_items, total = total, counter = counter))

def email(to_email, subject, message):
    from_email = settings.EMAIL_HOST_USER
    send_mail(subject, message, from_email, to_email, fail_silently=False)

def accept_order(request, cart_items = None):
    form = AorderForm(request.POST or None)
    cart = Cart.objects.get(cart_id=_cart_id(request))
    UID = None
    WID = 0
    order_list=[]
    if request.user.is_authenticated:
        current_user = request.user
        UID = current_user.id
    if form.is_valid():
        instance = form.save(commit=False)
        wh = Warehouse.objects.all()
        w1 = Warehouse.objects.get(whid = 0)
        len_max =((w1.x - instance.desx)**2 +(w1.y - instance.desy)**2)**0.5
        for w in wh:
            len_temp = ((w.x - instance.desx)**2 +(w.y - instance.desy)**2)**0.5
            if len_temp < len_max:
                len_max = len_temp
                WID = w.whid
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for c in cart_items:
            a = Aorder.objects.create( 
                    description=c.good.description,
                    amount=c.amount,
                    ups=instance.ups,
                    whid=WID,
                    desx=instance.desx,
                    desy=instance.desy,
                    ID=c.good.ID,
                    userid=UID,
                    email=instance.email,
                    )
            a.save()
            order_list.append(a)
            good = get_object_or_404(Good, ID=c.good_id)
            cart_item = CartItem.objects.get(good=good, cart=cart)
            cart_item.delete()
        to_email = [instance.email,]
        subject  = "Order Confirmation from mini Amazon"
        message  = "You order number list is: " + "\n"
        for a in order_list:
            message += "Order number is " + str(a.ordernum) + "\n"
        email(to_email, subject, message)
    return render(request, 'order_success.html', {'order_list':order_list})

web-app/miniAmazon/cart/templates/cart.html
{% extends "base.html" %}
{% load staticfiles %}
{% block metadescription %}
	Cart Page. Proceed to review your items and place the order.
{% endblock %}
{% block title %}
	Cart - Mini Amazon
{% endblock %}
{% block content %}
	{% if not cart_items %}
	<div>
		<div>
			<br>
			<h1 class="text-center my_title">
				Your shopping cart is empty.
			</h1>
			<br>
			<p class="text-center">
				Please click <a href="{% url 'shop:allGoodCat' %}">here</a> to countinue shopping.
			</p>
		</div>
	</div>
	{% else %}
	<div>
		<div class="text-center">
			<br>
			<h1 class="text_center my_title">
				Your Shopping Cart
			</h1>
			<br>
		</div>
	</div>
	<div class="row mx-auto">
		<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
			<table class="table my_custom_table">
				<thead class="my_custom_thead">
					<tr>
						<th colspan="5">
							Your items
						</th>
					</tr>
				</thead>
				<tbody>
					{% for cart_item in cart_items %}
					<tr>
						<td>
							<a href="cart_item.good.get_absolute_url"><img src="{{cart_item.good.image.url }}" alt="" class="float-left rounded custom_image"></a>
						</td>
						<td class="text-left">
							{{cart_item.good.description}}
							<br>
							SKY: {{cart_item.good.ID}}
							<br>
							Amount: {{cart_item.amount}}
						</td>
						<td>
							{{cart_item.sub_total}}
						</td>
						<td>
							<a href="{% url 'cart:add_cart' cart_item.good.ID %}" class="custom_a"><i class="fas fa-plus-circle custom_icon"></i></a>&nbsp;<a href="{% url 'cart:cart_remove' cart_item.good.ID %}" class="custom_a"><i class="fas fa-minus-circle custom_icon"></i></a>&nbsp;<a href="{% url 'cart:full_remove' cart_item.good.ID %}" class="custom_icon"><i class="fas fa-trash-alt custom_icon"></i></a>
						</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
		<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
			<table class="table my_custom_table">
				<thead class="my_custom_thead">
					<tr>
						<th colspan="5">
							Checkout
						</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>
							Please review your shopping cart items befor proceeding with the order payment.
						</td>
					</tr>
					<tr>
						<td class="text-left">
							Your total is: <strong>{{counter}}</strong>
						</td>
					</tr>
				</tbody>
			</table>
			<div class="mx-auto">
				<a href="{% url 'shop:allGoodCat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>	
				<a href="{% url 'cart:create_order' %}" class="btn btn-secondary btn-block my_custom_button">Checkout</a>
			</div>
		</div>
	</div>
	<br>
	{% endif %}
{% endblock %}

web-app/miniAmazon/cart/templates/order.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block metadescription %}
	New Order Page. Proceed to review your items and place the order.
{% endblock %}
{% block title %}
	Order - Mini Amazon
{% endblock %}
{% block content %}
    <div>
		<div class="text-center">
			<br>
			<h1 class="text_center my_title">
				Your Shopping Items
			</h1>
			<br>
		</div>
	</div>
	<div class="row mx-auto">
		<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
			<table class="table my_custom_table">
				<thead class="my_custom_thead">
					<tr>
						<th colspan="5">
							Your items
						</th>
					</tr>
				</thead>
				<tbody>
					{% for cart_item in cart_items %}
					<tr>
						<td>
							<a href="cart_item.good.get_absolute_url"><img src="{{cart_item.good.image.url }}" alt="" class="float-left rounded custom_image"></a>
						</td>
						<td class="text-left">
							{{cart_item.good.description}}
							<br>
							SKY: {{cart_item.good.ID}}
							<br>
							Amount: {{cart_item.amount}}
						</td>
						<td>
							{{cart_item.sub_total}}
						</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
		<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
			<table class="table my_custom_table">
				<thead class="my_custom_thead">
					<tr>
						<th colspan="5">
							Checkout
						</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>
							Click the submit button to process checkout.
						</td>
					</tr>
					<tr>
						<td class="text-center">
							Your total is: <strong>{{total}}</strong>
						</td>
					</tr>
				</tbody>
			</table>
			<div class="mx-auto">
				<form method='POST' action='accept_order/'>{% csrf_token %}
					{{aorderform | crispy}}
					<input class="bun bun-secondary btn-block my_custom_butoon" type='submit' value='submit'/>
				</form>
			<div>
			<!--<div class="mx-auto">-->
				<!--<a href="% url 'shop:allGoodCat'%}" class="btn btn-secondary btn-block my_custom_button">Submit</a>-->
			<!--</div>-->
		</div>
	</div>
<br>
{% endblock %}

web-app/miniAmazon/cart/templates/order_success.html
{% extends "base.html" %}
{% load staticfiles %}
{% block metadescription %}
	Order Detail Page.
{% endblock %}
{% block title %}
	Order - Mini Amazon
{% endblock %}
{% block content %}
	<div>
		<div class="text-center">
			<br>
			<h1 class="text_center my_title">
				Your Order List:
			</h1>
			<br>
		</div>
	</div>
	<div class="row mx-auto">
		<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
			<table class="table my_custom_table">
				<thead class="my_custom_thead">
					<tr>
						<th colspan="5">
							Your Order
						</th>
					</tr>
				</thead>
				<tbody>
					{% for a in order_list %}
					<tr>
						<td class="text-left">
							Order Number: {{a.ordernum}}
							<br>
							Description: {{a.description}}
							<br>
							Amount: {{a.amount}}
							<br>
							ShipID: {{a.goodid}}
							<br>
						</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
		<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
			<div class="mx-auto">
				<a href="{% url 'shop:allGoodCat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>	
			</div>
		</div>
	</div>
	<br>
{% endblock %}